### ISSUE TITLE
Users should be able to pass arbitrary options to the tracks

### ISSUE THREAD

**Issue by armish** [hammerlab/pileup.js#313]
We currently hardcode the decision to show specific visual components within the track. Ideally, users should be able to pass options to override these settings. For example:

- [x] connect paired reads (#110)
- [ ] show mismatches in the coverage (#233)
- [ ] show center line in the pileup track (#311)

**Comment by danvk** [comment]
@armish was there a particular reason you wanted to optionalize showing mismatches & the center line?

Desktop IGV has an option for the coverage mismatch AF threshold, but not an explicit option to turn off mismatch rendering. So far as I can tell it doesn't have an option to turn off the center line.

I guess I'm just saying... these features are so great, can you think of a scenario where you'd want to turn them off? :)

**Comment by armish** [comment]
yeah, agree that it doesn't make sense to turn the visualization options off at this point; but I feel bad about setting a hard threshold for the variant frequency, so maybe we can at least do that optional? :)

**Comment by danvk** [comment]
IGV does have an option to show the center line:
http://www.broadinstitute.org/igv/Preferences#Alignments
